config/routes.rb
Rails.application.routes.draw do


  resources :messages , only: [:new, :create, :index]
  # This line mounts Spree's routes at the root of your application.
  # This means, any requests to URLs such as /products, will go to Spree::ProductsController.
  # If you would like to change where this engine is mounted, simply change the :at option to something different.
  #
  # We ask that you don't use the :as option here, as Spree relies on it being the default of "spree"

  mount Spree::Core::Engine, at: "/"

  get '/tracker', to: 'shippings#tracker', as: 'track_shipment'
  get '/home_page' => 'spree/home#home_page'
  get '/catalog', to: 'catalog#index', as: 'catalog'

  get '/about', to: 'static#about', as: 'about'
  get '/terms', to: 'static#terms', as: 'terms'
  get '/empresa', to: 'static#empresa', as: 'empresa'
  get '/servicios', to: 'static#services', as: 'services'
  get '/contact', to: 'messages#new', as: 'contact'
  get '/test', to: 'static#test', as: 'test'
  get '/logistica', to: 'static#logistica', as: 'logistica'
  get '/alquiler', to: 'static#alquiler', as: 'alquiler'
  get '/mantenimiento', to: 'static#mantenimiento', as: 'mantenimiento'
  get '/asesoria', to: 'static#asesoria', as: 'asesoria'
  get '/contactenos', to: 'static#contactenos', as: 'contactenos'

  post '/subs', to: 'subscriptions#create', as: 'newsubscription'

  resources :subscriptions
  post 'contact-message', to: 'messages#create', as: 'contact-message'
  Spree::Core::Engine.add_routes do
    post '/cotizacion', to: 'orders#cotizare', as: 'cotizare'

    namespace :admin do
      resources :subscriptions
    end
    resources :subscriptions
  end


  get '/faq', to: 'static#faq', as: 'faq'

  get '/privacy_policy', to: 'static#privacy_policy', as: 'privacy_policy'
  #get '/contact', to: 'static#security', as: 'security'

  # You can have the root of your site routed with "root"
  # root 'welcome#index'

  # Example of regular route:
  #   get 'products/:id' => 'catalog#view'

  # Example of named route that can be invoked with purchase_url(id: product.id)
  #   get 'products/:id/purchase' => 'catalog#purchase', as: :purchase

  # Example resource route (maps HTTP verbs to controller actions automatically):
  #   resources :products

  # Example resource route with options:
  #   resources :products do
  #     member do
  #       get 'short'
  #       post 'toggle'
  #     end
  #
  #     collection do
  #       get 'sold'
  #     end
  #   end

  # Example resource route with sub-resources:
  #   resources :products do
  #     resources :comments, :sales
  #     resource :seller
  #   end

  # Example resource route with more complex sub-resources:
  #   resources :products do
  #     resources :comments
  #     resources :sales do
  #       get 'recent', on: :collection
  #     end
  #   end

  # Example resource route with concerns:
  #   concern :toggleable do
  #     post 'toggle'
  #   end
  #   resources :posts, concerns: :toggleable
  #   resources :photos, concerns: :toggleable

  # Example resource route within a namespace:
  #   namespace :admin do
  #     # Directs /admin/products/* to Admin::ProductsController
  #     # (app/controllers/admin/products_controller.rb)
  #     resources :products
  #   end
end

app/models/message.rb
class Message < ApplicationRecord

   validates :email, presence: true
   validates_format_of :email, :with => /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\z/i

end

app/models/spree/message.rb
module Spree
  class Message
    include ActiveModel::Model
    include ActiveModel::Conversion
    include ActiveModel::Validations

    attr_accessor :name, :email, :product, :phone, :website, :details, :aditional

    validates :name, :email, :product, presence: true
  end
end

app/controllers/messages_controller.rb
class MessagesController <  Spree::StoreController
  def create
    @message = Spree::Message.new(message_params)
    if @message.valid?
      Spree::HomeMessageMailer.new_message(params[:message]).deliver
      redirect_to root_path, notice: "Hemos recibido su solicitud. Alguien de nuestro 
                                          equipo lo estará contactando"
    else
      flash[:alert] = "Un error ocurrió al momento de mandar el mensaje, intentelo más tarde o  
                        contacte al equipo de soporte."
      redirect_to root_path
    end
  end

private
  def message_params
    params.require(:message).permit(:name, :product, :email, :phone, :website, :details, :aditional)
  end
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/views/messages/_form.html.erb
<%= form_for(message, :html => {:class => "findUseform"}) do |f| %>
  <% if message.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(message.errors.count, "error") %> prohibited this message from being saved:</h2>
      <ul>
      <% message.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">

    <%= f.text_field :name, class: "form-control input-lg" %>
  </div>

  <div class="field">

    <%= f.text_field :email, class: "form-control input-lg"  %>
  </div>

  <div class="field">
    <%= f.label :subject %>
    <%= f.text_field :subject, class: "form-control input-lg"  %>
  </div>

  <div class="field">
    <%= f.text_area :content, class: "form-control input-lg" %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/messages/edit.html.erb
<h1>Editing Message</h1>

<%= render 'form', message: @message %>

<%= link_to 'Show', @message %> |
<%= link_to 'Back', messages_path %>

app/views/messages/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Messages</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Email</th>
      <th>Subject</th>
      <th>Content</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @messages.each do |message| %>
      <tr>
        <td><%= message.name %></td>
        <td><%= message.email %></td>
        <td><%= message.subject %></td>
        <td><%= message.content %></td>
        <td><%= link_to 'Show', message %></td>
        <td><%= link_to 'Edit', edit_message_path(message) %></td>
        <td><%= link_to 'Destroy', message, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Message', new_message_path %>

app/views/messages/new.html.erb
<section class="findUs text-center">
  <h1>CONTACT US</h1>
  <p>
    Ut enim ad minim veniam, quis nostrud exercitation ullamco
    laboris nisi ut aliquip ex ea commodo consequat.
  </p>
  <div class="row">
    <div class="col-md-4 col-md-offset-1 text-left contanctCompanyInf">
      <div class="mb-32">
        <span class="title">Address</span>
        <br>
        <span class="subtitle">Chicago, IL 60606, 123, New Lenox</span>
      </div>
      <div class="mb-32">
        <span class="title">We are open</span>
        <br>
        <span class="subtitle">Open hours: 8.00-18.00 Mon-Sat</span>
      </div>
      <div class="mb-32">
        <span class="title">Phone</span>
        <br>
        <span class="subtitle">123-456-7890, 123-456-7890</span>
      </div>
      <div class="mb-32">
        <span class="title">E-mail</span>
        <br>
        <span class="subtitle">info@yoursite.com</span>
      </div>
    </div>
    <div class="col-md-6">
      <%= form_for(@message, :html => {:class => "findUseform"}) do |f| %>
        <% if @message.errors.any? %>
          <div id="error_explanation">
            <h2><%= pluralize(@message.errors.count, "error") %> prohibited this message from being saved:</h2>

            <ul>
            <% @message.errors.full_messages.each do |message| %>
              <li><%= message %></li>
            <% end %>
            </ul>
          </div>
        <% end %>
        <div class="field">

          <%= f.text_field :name, class: "form-control input-lg", placeholder:"Name *" %>
        </div>

        <div class="field">

          <%= f.text_field :email, class: "form-control input-lg", placeholder:"Email *"  %>
        </div>

        <div class="field">

          <%= f.text_field :subject, class: "form-control input-lg", placeholder:"Subject *"   %>
        </div>

        <div class="field">
          <%= f.text_area :content, class: "form-control input-lg", placeholder:"Message *" %>
        </div>

        <div class="actions">
          <%= f.submit 'Send Message',  class:"btn send-message" %>
        </div>
      <% end %>
    </div>
  </div>
</section>
<section class="findUs text-center"> 
    <h1>HOW TO FIND US</h1>
</section>
<section id="map">
      <iframe
      width="100%"
      height="450"
      frameborder="0" style="border:0"
      src="https://www.google.com/maps/embed/v1/place?key=AIzaSyDlbJ_XRVze2LtvaIBXH8Libsn6c6PWU1Q
        &q=Space+Needle,Seattle+WA" allowfullscreen>
    </iframe>
</section>

app/views/messages/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @message.name %>
</p>

<p>
  <strong>Email:</strong>
  <%= @message.email %>
</p>

<p>
  <strong>Subject:</strong>
  <%= @message.subject %>
</p>

<p>
  <strong>Content:</strong>
  <%= @message.content %>
</p>

<%= link_to 'Edit', edit_message_path(@message) %> |
<%= link_to 'Back', messages_path %>